import { Product } from './types';

export const mockProducts: Product[] = [
  {
    id: 'PROD001',
    tenantId: 'tenant-1',
    name: 'Classic White T-Shirt',
    description: 'A classic crewneck t-shirt in white, made from 100% premium cotton.',
    sku: 'TS-CW-M',
    categoryId: 'tops',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    stock: 15,
    price: 25.0,
    costPrice: 15.0,
    imageUrl: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb&w=600',
    supplierId: 'SUP001',
    averageDailySales: 5,
    leadTimeDays: 7,
  },
  {
    id: 'PROD002',
    tenantId: 'tenant-1',
    name: 'Wireless Over-Ear Headphones',
    description: 'High-fidelity wireless over-ear headphones with noise-cancellation.',
    sku: 'HD-WOH-BLK',
    categoryId: 'accessories',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    stock: 35,
    price: 149.99,
    costPrice: 90.0,
    imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb&w=600',
    supplierId: 'SUP002',
    averageDailySales: 2,
    leadTimeDays: 14,
  },
  {
    id: 'PROD003',
    tenantId: 'tenant-1',
    name: 'Artisanal Coffee Beans',
    description: 'A 1kg bag of artisanal whole coffee beans, single-origin from Ethiopia.',
    sku: 'CB-AO-1KG',
    categoryId: 'essentials',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    stock: 50,
    price: 35.5,
    costPrice: 20.0,
    imageUrl: 'https://images.unsplash.com/photo-1511920183353-3c9c6b738e38?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb&w=600',
    supplierId: 'SUP003',
    averageDailySales: 10,
    leadTimeDays: 5,
  }
];
